#!/usr/bin/with-contenv bash

__nginx_conf_target=${UDS_PROXY_CONF_LOCATION:-"/etc/nginx"}

echo "[UDS_proxy] generating nginx configuration at $__nginx_conf_target"

if [ ! -d "$__nginx_conf_target" ]; then
  echo "$__nginx_conf_target does not exist! attempting to create it"
  mkdir -p $__nginx_conf_target
fi

__nginx_conf_file="$__nginx_conf_target""/nginx.conf"

# write the start of the nginx.conf file
echo 'events {
    worker_connections 1024;
}

http {' >> $__nginx_conf_file

# write the proxy configurations
__sock_location=${UDS_PROXY_SOCK_LOCATION:-/comm}
env | while IFS= read -r line; do
  __env_value=${line#*=}
  __env_name=${line%%=*}
  if [[ "$__env_name" =~ ^UDS_PROXY_HOST_([0-9A-Za-z_]+)$ ]]; then
    __sock_name=${BASH_REMATCH[1]}
    __target=$__env_value
    echo "proxying $__target to $__sock_location/$__sock_name.sock"
    echo  "
    server {
       listen unix:$__sock_location/$__sock_name.sock;

       proxy_set_header Host \$host;
       proxy_set_header X-Forwarded-For \$remote_addr;

       location / {
           proxy_pass http://$__target;
       }
    }">> $__nginx_conf_file
  fi

done

echo '
}' >> $__nginx_conf_file

echo "[UDS_proxy] nginx configuration written to $__nginx_conf_file"
