#!/usr/bin/with-contenv bash

## Ubuntu
if [ -f /usr/bin/apt ]; then
    echo "ubuntu"

fi
# Alpine
if [ -f /sbin/apk ]; then
    echo "alpine"
fi
echo "nginx" >> /mod-repo-packages-to-install.list
mkdir -p /etc/nginx && mv /etc/default/nginx.conf /etc/nginx/nginx.conf && echo "moved the thing"